name: Website deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    
    - name: SSH into digitalocean droplet and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USER }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        port: ${{ secrets.DIGITALOCEAN_PORT }}
        script: |
          cd /var/www/samuelogu.com
          git pull
          npm install
          npm run build
          pm2 restart samuelogu.com
          
